### ISSUE TITLE
Errors with lookup

### ISSUE THREAD

**Issue by BenCoffeed** [jhaals/ansible-vault#56]
### Problem Description:
I'm trying to use the lookup plugin in Ansible 2.3 in order to look up secrets in my playbooks. However, when I try to run the playbooks, Ansible hangs in the 'gathering facts' phase.

### Output:
` ansible-playbook app.yml --extra-vars "target_hosts=app01"`
```
TASK [Gathering Facts] *************************************************************************************************************************************************************************************
objc[38943]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called.
objc[38943]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
```

### Playbook:
```yml
---
- name: Configure App server
  hosts: "{{ target_hosts| default('app-servers') }}"

  vars:
    runtime_env: production
    api_key: "{{ lookup('vault','secret=secret/production/api_key','value') }}"
    aws: "{{ lookup('vault', 'aws/creds/common_get_s3_build') }}"

  environment:
    AWS_ACCESS_KEY: "{{ aws.access_key }}"
    AWS_SECRET_KEY: "{{ aws.secret_key }}"

  pre_tasks:
    - name: install dependencies for ansible
      apt: name={{ item }} state=latest
      with_items:
        - python-psycopg2
        - python-boto

  roles:
    - common
    - { role: users, include_dev: false }
    - postgres
    - { role: production, server_role: app }

```
### Environment information:
- MacOS High Sierra Public Beta
- Python 2.7.10
- Ansible 2.3.1.0
- VAULT_ADDR and VAULT_TOKEN are set in zshrc

`ansible.cfg`
```
. . .
lookup_plugins     = ./lookup_plugins
. . .
```

`ls -al lookup_plugins/`
```
total 0
drwxr-xr-x   3 btennant  staff    96 Aug 10 16:34 .
drwxr-xr-x  48 btennant  staff  1536 Aug 10 20:18 ..
drwxr-xr-x   9 btennant  staff   288 Aug 10 16:17 jhaals.ansible-vault
```
